### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by ghost** [grantwinney/hide-comments-in-chrome#1]
I have to use your plugin,
Can you create a separate plugin, that is, "expand all comments" plugin?
thx.

**Comment by grantwinney** [comment]
I don't have a lot of free time to write random plugins, but you're welcome to use any ideas from this one if you decide to create your own. If you're brand new to writing extensions, this [getting started tutorial](https://developer.chrome.com/extensions/getstarted) should help.
